#!/usr/bin/perl
#-------------------------------------------------+
#    [APM] This script was generated by amp.pl    |
#    [APM] Created time: 2016-01-13 09:03:59      |
#-------------------------------------------------+
# name: GDHR.pl
# func: 
# version:: 0.1

use strict;
use warnings;

use File::Basename qw/basename/;
use FindBin qw($Bin);
use lib "$Bin/lib/";
use GDHR;

my $flow1_desc = <<HTML;
样品提取总RNA后，去除核糖体RNA，然后用Rnase R酶降解线性RNA。得到的环状RNA中加入fragmentation buffer使其片断成为短片段，再以片断后的环状RNA为模板，
用六碱基随机引物（random hexamers）合成cDNA第一链，并加入缓冲液、dNTPs、RNase H和DNA polymerase I合成cDNA第二链，
经过QiaQuick PCR试剂盒纯化并加EB缓冲液洗脱经末端修复、加碱基A，加测序接头，再经琼脂糖凝胶电泳回收目的大小片段，并进行PCR扩增，
从而完成整个文库制备工作，构建好的文库用Illumina HiSeq<sup>TM</sup> 2500进行测序。
HTML

my $flow2_desc = <<HTML;
得到下机数据后，首先将会对其进行过滤，得到HQ Clean Reads。每个样品的 HQ Clean Reads 与 参考基因组 分别进行分别 TopHat 比对，得到每个样品的比对结果。
从比对结果中提取Unmapped Reads，然后截取每一条Unmapped Reads的两端（默认20bp），得到Anchors Reads。用Anchors Reads再一次比对到基因组上，
将得到的比对结果提交给find_circ软件鉴定出环状RNA。得到鉴定的环状RNA后，主要分三部分进行分析。
1）环状RNA统计，包括统计Reads类型，环状RNA类型，环状RNA分布等；
2）表达量计算与差异分析，包括表达量计算和样品比较组或分组比较组差异表达分析；
3）数据库注释与靶向预测，包括对环状RNA进行circBase数据库注释，对被注释的环状RNA定义为已存在环状RNA，未被注释的环状RNA定义为新预测环状RNA，
然后对已存在环状RNA进行starBase小RNA靶向关系注释，对数据库中已有靶向关系定义为已存在靶向关系，然后对全体环状RNA进行小RNA靶向预测，得到新预测靶向关系。
获得靶向关系后，我们可从mirTarBase中找到已存在的小RNA与mRNA靶向关系，利用以上信息可构建网络图。
HTML

my $outdir = "test";
my $report = GDHR->new('-outdir'=>$outdir,-pipe=>"meta Genome");

my $section = $report->section(id=>"introduction",-page_head=>1);
$section->menu("技术简介");
$section->submenu("实验简介");
$section->img2html(-file=>"image/flow_001.png",-name=>"实验流程图",-desc=>$flow1_desc);
$section->submenu("信息分析简介");
$section->img2html(-file=>"image/flow_002.png",-name=>"信息分析流程图");

$section = $report->section(id=>"seq_stat",-break=>1);
$section->menu("测序评估",-help=>"seq_stat.html");
$section->submenu("测序质量评估",-help=>"seq_stat.html#sub_1");
$section->tsv2html(-file=>"$outdir/05.taxonomy/all.scaftigs.profiling.xls",-name=>"scaftigs物种注释及丰度表",-header=>1,-max_chars=>12);
$section->submenu("碱基组成与质量分析");
my @names = ("A","B","C");
my @files = ("../01.reads/01.filter/A.readsClass.png","../01.reads/01.filter/B1.readsClass.png","../01.reads/01.filter/B2.readsClass.png");
my @desc = ("样品A clean data 分布图","样品B1 clean data 分布图","样品B2 clean data 分布图");
$section->imgs2html(-files=>\@files,-names=>\@names,-desc=>\@desc,-id=>3);

$section->break;

$report->seq_stat(-dir=>"01.reads/01.filter/");

$section = $report->section(id=>"assembly");
$section->menu("组装");
$section->desc("assembly result");
$section->img2html2(-file1=>"../02.assembly/A/A.scaftigs.fasta.length_distribution.png",
	-file2=>"../02.assembly/B1/B1.scaftigs.fasta.length_distribution.png",
	-name1=>"样本<span class=\"pic_table_strong\">A</span>组装结果长度分布",
	-name2=>"样本<span class=\"pic_table_strong\">B1</span>组装结果长度分布",
	-desc2=>"说明：X轴表示Scaftigs的长度值，大于3000统一看做3000；左侧的Y轴（Frequence#）表示Scaftigs的数目（频数）， 右侧的Y轴（Percentage%）表示Scaftigs数目占Scaftigs总数的百分比。");

@files = ("../02.assembly/A/A.scaftigs.fasta","../02.assembly/A/A.scaftigs.fasta.length");
@desc = ("scaftigs文件(fasta格式)","scaftigs长度统计文件");
$section->files2list(-files=>\@files,-desc=>\@desc);

$report->write();
$report->pack(-format=>"zip");
