#!/usr/bin/perl
#-------------------------------------------------+
#    [APM] This script was generated by amp.pl    |
#    [APM] Created time: 2016-03-31 09:26:28      |
#-------------------------------------------------+
# name: reads_report.pl
# func: 
# version:: 0.1

use strict;
use warnings;

use File::Basename qw/basename/;
use FindBin qw($Bin);

use lib "$Bin/lib/";
use GDHR;

my $dir = shift;

my $report = GDHR->new('-outdir'=>$dir,-pipe=>"Reads QC Report");
$report->seq_stat(-dir=>"./");
$report->write();
$report->pack(-format=>"zip")
