package GDHR;
#-------------------------------------------------+
#    [APM] This moudle was generated by amp.pl    |
#    [APM] Created time: 2016-01-13 08:53:56      |
#-------------------------------------------------+
=pod

=head1 Name

GDHR -- GeneDenovo HTML Report moudle

=head1 Synopsis

This module is not meant to be used directly

=head1 Feedback

Author: Peng Ai
Email:  aipeng0520@163.com

=head1 Version

Version history

=head2 v1.0

Date: 2016-01-13 08:53:56

=cut

use strict;
use warnings;

use GDHR::DEBUG;
use GDHR::HTML;

require Exporter;
our @ISA = qw(Exporter);



sub new 
{
	my ($class,%opts) = @_;
	
	# check the ENV
	my $root = $ENV{'GDHR_PATH'} or die "GDHR_PATH is not defined in your ENV!";
	
	my $report = {};
	$report->{path}->{root} = $root;
	
	bless $report , $class;

	# init the report dir 
	$report->init_report(%opts);
	
	return $report;
}

sub init_report
{
	my ($class,%opts) = @_;
	
	# create the outdir 
	my $outdir = $opts{'-outdir'} || ".";
	mkdir $outdir unless -d $outdir;
	$class->{path}->{outdir} = $outdir;

	# the report 's pipe type
	my $pipe = $opts{'-pipe'} || "补充";
	$class->{pipe} = $pipe;
	
	# the main index name 
	my $name = $opts{'-name'} || "index";
	$class->{name} = $name;

	# copy the config files to outdir
	$class->cp_conf_files();
	
	# create the main html file
	$class->init_index_html();
	$class->init_main_html();
}

sub cp_conf_files
{
	my $class = shift;
	
	my $outdir = $class->{path}->{outdir};
	my $root = $class->{path}->{root};
	my $conf_dir = "$root/conf";
	
	mkdir "$outdir/src" unless -d "$outdir/src";

	system("cp -r $conf_dir/* $outdir/src");
	timeLOG("init the config done ... ");
}

sub init_index_html
{
	my $class = shift;
	my $pipe = $class->{pipe};
	my $outdir = $class->{path}->{outdir};
	
	my $html = <<HTML;
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<!-- 基本信息 -->
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>基迪奥生物 结题报告</title>
		
		<!-- CSS文档 -->
		<link rel="stylesheet" type="text/css" href="src/css/index.css" />
		
		<!-- JS脚本 -->
		<script src="src/js/jquery-1.9.1-min.js"></script>
	</head>
	<body>
		<!-- 结题报告页眉 -->
		<section>
			<div id="header_banner">
				<div id="banner_logo"></div>
				<div id="banner_title">基迪奥生物 <span> $pipe分析 </span> 结题报告</div>
				<div id="banner_bg_image"></div>
			</div>
		</section>
		
		<!-- 结题报告主内容 -->
		<section>
			<iframe id="iframepage" src="src/content.html"></iframe>
		</section>
		
		<!-- JS脚本初始化 -->
		<script language="javascript">
			function frameresize(){
				var iframeheight = \$(window).height();
				\$('#iframepage').css('height', iframeheight - 85 + 'px');
			};
			if(window.attachEvent){
				document.getElementById("iframepage").attachEvent('onload', frameresize);
			}
			else{
				document.getElementById("iframepage").addEventListener('load', frameresize, false);
			} 
			\$(window).resize(frameresize);
			frameresize();
		</script>
	</body>
</html>
HTML
	
	open OUT , ">" , "$outdir/index.html" or die $!;
	print OUT $html;
	close OUT;
	timeLOG("The index html report 'content.html' was create done :)");
}

sub init_main_html
{
	my $class = shift;

	my $html = "";
	$class->{html} = $html;
}

sub section
{
	my ($class,%opts) = @_;
	my $section = GDHR::HTML->section(%opts);
	
	push @{$class->{section}} , $section;
	return $section;
}

sub write
{
	my ($class,%opts) = @_;
	
	my $outdir = $class->{path}->{outdir};
	
	my $head = $class->main_html_head();
	my $tail = $class->main_html_tail();
	
	my $html = $class->{html};
	foreach my$section (@{$class->{section}})
	{
		$html .= $section->innerHTML;
	}
	
	open OUT , ">" , "$outdir/src/content.html";
	print OUT $head;
	print OUT $html;
	print OUT $tail;
	close OUT;
	
	timeLOG("The content html report 'content.html' was create done :)");
}

# pack the report folder, this function will use the pack cmd of system, so just for Linux now.
# support pack format: gz, bz2, zip, rar
sub pack
{
	my ($class,%opts) = @_;
	
	my $outdir = $class->{path}->{outdir};
	my $format = $opts{'-format'} || "bz2";
	
	my $cmd = "";
	if ($format eq "bz2")
	{
		$cmd = "tar -czf $outdir.tar.bz2 $outdir";
	}
	elsif ($format eq "gz")
	{
		$cmd = "tar -cjf $outdir.tar.gz $outdir";
	}
	elsif ($format eq "zip")
	{
		$cmd = "zip -r $outdir.zip $outdir";
	}
	elsif ($format eq "rar")
	{
		$cmd = "rar a -r $outdir.rar $outdir";
	}
	else 
	{
		ERROR("pack format error, now just support format: gz, bz2, zip, rar.",$format);
	}
	
	system("$cmd 1>/dev/null");
	timeLOG("The html report has been packed :)");
}

sub main_html_head
{	
	my $head = <<HTML;
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<!-- 基本信息 -->
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>基迪奥生物 结题报告</title>
		
		<!-- CSS文档 -->
		<link rel="stylesheet" type="text/css" href="css/report.css" />
		<link rel="stylesheet" type="text/css" href="css/jumpto.css" />
		<link rel="stylesheet" type="text/css" href="css/easy-responsive-tabs.css" />
		
		<!-- JS脚本 -->
		<script src="js/jquery-1.9.1-min.js"></script>
		<script src="js/modernizr-min.js"></script>
		<script src="js/jquery.jumpto-min.js"></script>
		<script src="js/jquery.nicescroll-min.js"></script>
		<script src="js/easyResponsiveTabs-min.js"></script>
		<script src="js/show_help-min.js"></script>
		
	</head>
	<body>
		<div id="report_body">
HTML
	return $head;
}

sub main_html_tail
{
	my $tail = <<HTML;
		</div>
		
		<div id="goTop" style="display:none;">
			<a title="返回顶部" class="backtotop">
				<img class="back-top" src="image/goTop.jpg">
			</a>
		</div>
		
		<!-- 帮助文档窗口 -->
		<div id="show_help">
			<h3>帮助文档</h3>
			<iframe id="help_page" name="help_page" src="http://www.genedenovo.com/"></iframe>
		</div>
		
		<!-- JS插件初始化 -->
		<script type="text/javascript">
			\$(document).ready(function() {
				\$("#report_body").jumpto({
					innerWrapper: "section",
					firstLevel: "> h3",
					secondLevel: "> h5",
					offset: 0,
					anchorTopPadding: 0,
					animate: 600,
					showTitle: "目录",
					closeButton: false
				});
				for (var i = 1; i <= 9; i++){
					\$('#resp-tabs-list' + i).niceScroll({cursoropacitymax:0.5,cursorwidth:"8px"});
					\$('#resp-tabs-container' + i).niceScroll({cursoropacitymax:0.5,cursorwidth:"8px"});
					\$('#parentVerticalTab' + i).easyResponsiveTabs({
						type: 'vertical', //Types: default, vertical, accordion
						width: 'auto', //auto or any width like 600px
						fit: true, // 100% fit in a container
						closed: 'accordion', // Start closed if in accordion view
						tabidentify: 'hor_' + i, // The tab groups identifier
						activate: function(event) { // Callback function if tab is switched
							var \$tab = \$(this);
							var \$info = \$('#nested-tabInfo2');
							var \$name = \$('span', \$info);
							\$name.text(\$tab.text());
							\$info.show();
						}
					});
				}
			});
			
			/****表格悬浮显示全部内容****/
			function messshow (info) {
			var str='<div class="topBg"><div class="toppicBox"><div class="inBox" style="text-align:center;"><br><textarea class="pinfo" cols=56>'+info+'</textarea><br><br></div><img class="topClose" width="27" height="27" src="image/topclose.png" onclick="topclose()"></div></div>';
				  \$("body").append(str);}

			function topclose(){
			\$(".topBg").remove();
			}

			\$(function(){
				\$(".abbrTab").each(function(){
				var len=\$(this).attr("data");
				var mess=\$(this).text();
				\$(this).attr("title",mess);
				if(mess.length>len-1){
				mess=mess.substring(0,len-1);
				mess +='<span class="brief">...</span>';
			}
				\$(this).html(mess);

				});

				\$(".brief").click(function(){
				var info=\$(this).parent().attr("title");
				  messshow (info);
				 });
			});
			
			\$('.hl_table tr').has('td').each(function(){
				\$(this).attr('onmouseover', 'this.style.backgroundColor = "#DDDDDD"');
				\$(this).attr('onmouseout', 'this.style.backgroundColor = "#FFFFFF"');
			});
			
			\$('.jumpto-first').css('maxHeight', (\$(window).height()*0.98 - 48) + 'px');
			\$('.jumpto-first').niceScroll({cursoropacitymax:0.5,cursorwidth:"6px",cursorborder:"0px"});
		</script>
	</body>
</html>	
HTML

	return $tail;
}
